name: campus_assistant
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.17.5
  collection: ^1.18.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.5.1
  flutter_sound_lite: ^8.5.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  image: ^4.1.7
  image_picker: ^1.1.1
  json_annotation: ^4.9.0
  mobile_scanner: ^5.1.0
  riverpod_annotation: ^2.3.5
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  json_serializable: ^6.8.0
  riverpod_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/ml_models/
    - assets/sounds/
